config/routes.rb
Coupons::Engine.routes.draw do
  patch '/coupons', to: 'coupons#batch'
  get '/coupons/apply', to: 'coupons#apply', as: 'apply_coupon', format: 'json'

  resources :coupons do
    get :remove, on: :member
    get :duplicate, on: :member
  end
end

app/controllers/coupons/application_controller.rb
class Coupons::ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include Coupons::Models
  helper Coupons::ApplicationHelper

  include PageMeta::Helpers
  helper_method :page_meta

  before_action :authorize

  private

  def authorize
    Coupons.configuration.authorizer.call(self)
  end
end

app/controllers/coupons/coupons_controller.rb
class Coupons::CouponsController < Coupons::ApplicationController
  def apply
    coupon_code = params[:coupon]
    amount = BigDecimal(params.fetch(:amount, '0.0'))
    options = Coupons
              .apply(params[:coupon], amount: amount)
              .slice(:amount, :discount, :total)
              .reduce({}) {|buffer, (key, value)| buffer.merge(key => Float(value)) }

    render json: options
  end

  def index
    paginator = Coupons.configuration.paginator
    @coupons = Coupons::Collection.new(paginator.call(Coupon.order(created_at: :desc), params[:page]))
  end

  def new
    @coupon = Coupon.new
  end

  def create
    @coupon = Coupon.new(coupon_params)

    if @coupon.save
      redirect_to coupons_path,
        notice: t('coupons.flash.coupons.create.notice')
    else
      render :new
    end
  end

  def edit
    @coupon = Coupon.find(params[:id])
  end

  def duplicate
    existing_coupon = Coupon.find(params[:id])
    attributes = existing_coupon.attributes.symbolize_keys.slice(:description, :valid_from, :valid_until, :redemption_limit, :amount, :type)
    @coupon = Coupon.new(attributes)
    render :new
  end

  def update
    @coupon = Coupon.find(params[:id])

    if @coupon.update(coupon_params)
      redirect_to coupons_path,
        notice: t('coupons.flash.coupons.update.notice')
    else
      render :edit
    end
  end

  def remove
    @coupon = Coupon.find(params[:id])
  end

  def destroy
    @coupon = Coupon.find(params[:id])
    @coupon.destroy!

    redirect_to coupons_path,
      notice: t('coupons.flash.coupons.destroy.notice')
  end

  def batch
    if params[:remove_action]
      batch_removal
    else
      redirect_to coupons_path,
        alert: t('coupons.flash.coupons.batch.invalid_action')
    end
  end

  private

  def batch_removal
    Coupon.where(id: params[:coupon_ids]).destroy_all

    redirect_to coupons_path,
      notice: t('coupons.flash.coupons.batch.removal.notice')
  end

  def coupon_params
    params
      .require(:coupon)
      .permit(:code, :redemption_limit, :description, :valid_from, :valid_until, :amount, :type)
  end
end

app/helpers/coupons/application_helper.rb
module Coupons::ApplicationHelper
  def coupon_discount(coupon)
    t("#{coupon.type}_html", scope: 'coupons.off', amount: coupon.amount)
  end

  def coupon_description(coupon)
    classes = ['ellipsis']

    if coupon.description?
      description = coupon.description
    else
      classes << 'mute'
      description = t('coupons.coupon.no_description')
    end

    content_tag :span, description, class: classes.join(' '), title: description
  end

  def redeemed(coupon)
    limit = t('coupons.limit_html', count: coupon.redemption_limit)
    t('coupons.redeemed_html', count: coupon.redemptions_count, limit: limit)
  end

  def expiration(coupon)
    if coupon.valid_until?
      l(coupon.valid_until, format: :coupon)
    else
      content_tag :span, t('coupons.coupon.dont_expire'), class: 'mute'
    end
  end
end

app/views/coupons/application/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="flash-message <%= type %>">
    <p>
      <%= message %>
    </p>

    <span class="flash-message-close">
      ×
    </span>
  </div>
<% end %>

app/views/coupons/application/_form_errors.html.erb
<% if record.errors.any? %>
  <div class="form-errors">
    <p>
      <%= t('coupons.form_error_description') %>
    </p>

    <ul>
      <% record.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/coupons/application/_header.html.erb
<header class="main-header">
  <h1><%= page_meta.title.simple %></h1>

  <div class="main-header-actions">
    <%= yield :page_action %>
  </div>
</header>

app/views/coupons/coupons/_coupon.html.erb
<tr class="coupon">
  <td>
    <%= check_box_tag 'coupon_ids[]', coupon.id %>
  </td>

  <td>
    <span class="tag">
      <%= coupon_discount(coupon) %>
    </span>
  </td>

  <td>
    <%= coupon_description(coupon) %>
  </td>

  <td class="text-center">
    <%= redeemed(coupon) %>
  </td>

  <td class="text-center">
    <%= expiration(coupon) %>
  </td>

  <td class="text-center">
    <%= link_to t('coupons.actions.edit'),
        edit_coupon_path(coupon),
        class: 'icon-button edit',
        title: t('coupons.actions.edit') %>

    <%= link_to t('coupons.actions.remove'),
        remove_coupon_path(coupon),
        class: 'icon-button remove',
        title: t('coupons.actions.remove') %>

    <%= link_to t('coupons.actions.duplicate'),
        duplicate_coupon_path(coupon),
        class: 'icon-button duplicate',
        title: t('coupons.actions.duplicate') %>
  </td>
</tr>

app/views/coupons/coupons/_coupons.html.erb
<%= form_tag coupons_path, method: 'patch', class: 'skip' do %>
  <div class="coupons-actions hidden">
    <div class="container">
      <span class="selected" data-one="<%= t('coupons.selected_rules.one') %>" data-other="<%= t('coupons.selected_rules.other') %>"></span>

      <div class="coupons-actions-buttons">
        <input type="submit" name="remove_action" class="button rounded red secondary" value="<%= t('coupons.coupon.buttons.remove_selected') %>">
      </div>
    </div>
  </div>

  <table class="coupons-table">
    <thead>
      <tr>
        <th class="checkbox">
          <input type="checkbox" class="main" name="coupon-selector">
        </th>

        <th>
          <%= t('coupons.columns.discount') %>
        </th>

        <th>
          <%= t('coupons.columns.description') %>
        </th>

        <th class="text-center">
          <%= t('coupons.columns.redeemed') %>
        </th>

        <th class="text-center">
          <%= t('coupons.columns.expiration') %>
        </th>

        <th class="actions">
        </th>
      </tr>
    </thead>

    <tbody>
      <%= render "coupons/list/#{Coupons.configuration.pagination_adapter}", coupons: coupons %>
    </tbody>
  </table>

  <%= render "coupons/pagination/#{Coupons.configuration.pagination_adapter}", coupons: coupons %>
<% end %>

app/views/coupons/coupons/_form.html.erb
<%= form_for coupon, as: 'coupon', url: url, builder: Coupons::FormBuilder, html: {class: 'form'} do |form| %>
  <%= render 'form_errors', record: coupon %>

  <div class="form-group">
    <div class="form-label">
      <%= form.label :code %>
      <%= form.hint  :code %>
    </div>

    <div class="form-control">
      <%= form.text_field :code, autofocus: true %>
      <%= form.error_for :code %>
    </div>
  </div>

  <div class="form-group">
    <div class="form-label">
      <%= form.label :description %>
      <%= form.hint  :description, 'foo' %>
    </div>

    <div class="form-control">
      <%= form.text_field :description %>
      <%= form.error_for :description %>
    </div>
  </div>

  <div class="form-group">
    <div class="form-label">
      <%= form.label :redemption_limit %>
      <%= form.hint  :redemption_limit %>
    </div>

    <div class="form-control">
      <%= form.number_field :redemption_limit, min: 0 %>
      <%= form.error_for :redemption_limit %>
    </div>
  </div>

  <div class="form-group">
    <div class="form-label">
      <%= form.label :type %>
      <%= form.hint  :type %>
    </div>

    <div class="form-control">
      <%= form.select :type, Coupons::CouponType.to_select, include_blank: true %>
      <%= form.error_for :type %>
    </div>
  </div>

  <div class="form-group">
    <div class="form-label">
      <%= form.label :amount %>
      <%= form.hint  :amount %>
    </div>

    <div class="form-control">
      <%= form.text_field :amount %>
      <%= form.error_for :amount %>
    </div>
  </div>

  <div class="form-group">
    <div class="form-label">
      <%= form.label :valid_from %>
      <%= form.hint  :valid_from %>
    </div>

    <div class="form-control">
      <%= form.date_select :valid_from, include_blank: true, start_year: Date.current.year, end_year: Date.current.year + 10 %>
      <%= form.error_for :valid_from %>
    </div>
  </div>

  <div class="form-group">
    <div class="form-label">
      <%= form.label :valid_until %>
      <%= form.hint  :valid_until %>
    </div>

    <div class="form-control">
      <%= form.date_select :valid_until, include_blank: true, start_year: Date.current.year, end_year: Date.current.year + 10 %>
      <%= form.error_for :valid_until %>
    </div>
  </div>

  <div class="form-actions form-group">
    <%= form.submit t(form.object.persisted? ? 'edit' : 'create', scope: 'coupons.coupon.buttons'), class: 'button rounded green' %>
  </div>

<% end %>

app/views/coupons/coupons/_no_coupons.html.erb
<div class="panel panel-no-coupons">
  <h1 class="panel-title"><%= t('coupons.blank_slate.no_coupons') %></h1>

  <div class="panel-body">
    <p>
      <%= t('coupons.blank_slate.no_coupons_description') %>
    </p>

    <p>
      <%= link_to t('coupons.new_coupon_button'), new_coupon_path, class: 'button rounded green' %>
    </p>
  </div>
</div>

app/views/coupons/coupons/edit.html.erb
<% content_for(:page_action) do %>
  <%= link_to t('coupons.actions.go_back'), coupons_path, class: 'button rounded gray' %>
<% end %>

<%= render 'form', coupon: @coupon, url: coupon_path(@coupon) %>

app/views/coupons/coupons/index.html.erb
<% content_for(:page_action) do %>
  <%= link_to t('coupons.new_coupon_button'), new_coupon_path, class: 'button rounded green' %>
<% end %>

<% if @coupons.any? %>
  <%= render 'coupons', coupons: @coupons %>
<% else %>
  <%= render 'no_coupons' %>
<% end %>

app/views/coupons/coupons/new.html.erb
<% content_for(:page_action) do %>
  <%= link_to t('coupons.actions.go_back'), coupons_path, class: 'button rounded gray' %>
<% end %>

<%= render 'form', coupon: @coupon, url: coupons_path %>

app/views/coupons/coupons/remove.html.erb
<% content_for(:page_action) do %>
  <%= link_to t('coupons.actions.go_back'), coupons_path, class: 'button rounded gray' %>
<% end %>

<div class="panel">
  <div class="panel-title">
    <%= t('coupons.are_you_sure_you_want_to_remove_html') %>
  </div>

  <div class="panel-body">
    <p>
      <%= t('coupons.you_cant_undo_removal_html') %>
    </p>

    <p>
      <%= button_to t('coupons.actions.confirm'), coupon_path(@coupon), method: 'delete', class: 'button rounded red' %>
      <%= link_to t('coupons.actions.cancel'), coupons_path %>
    </p>
  </div>
</div>

app/views/coupons/list/_kaminari.html.erb
<%= render coupons %>

app/views/coupons/list/_paginate.html.erb
<%= render coupons, paginate: true, size: Coupons.configuration.per_page %>

app/views/coupons/pagination/_kaminari.html.erb
<%= paginate coupons %>

app/views/coupons/pagination/_paginate.html.erb
<%= paginate coupons, size: Coupons.configuration.per_page %>

app/views/layouts/coupons/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%#= page_meta %>
  <%= stylesheet_link_tag 'coupons' %>
</head>
<body>
  <div class="page container">
    <%= render 'header' %>

    <div class="content">
      <%= render 'flash_messages' %>
      <%= yield %>
    </div>
  </div>

  <%= javascript_include_tag 'coupons' %>
</body>
</html>